baseURL = 'https://computerwizard.livekiersted.com/'
languageCode = 'en-us'
title = 'Live Kiersted Computer Wizardry'
theme = 'hugo-scroll'
layoutDir = 'hugo-base/layouts'
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
ignoreFiles = [ ".*/README.md" ]

[params]
    favicon = "images/computer favicon.png"
    hidedesignbyline = true
    title = "Live Kiersted"
    description = "Tech Consulting"
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files